#ifndef TOKENWATCHROO_H
#define TOKENWATCHROO_H

// C API of libtokenwatchroo.a (Scala Native static library).
//
// Threading contract (design doc section 7): call every function from the main thread only.
// ScalaNativeInit must be called first, then tw_start. The library invokes tw_callback from its own
// worker threads with a JSON envelope that is valid only during the call; copy it and dispatch to the
// main queue. Never call a tw_* function from inside the callback.

#ifdef __cplusplus
extern "C" {
#endif

typedef void (*tw_callback)(const char *json, void *ctx);

// Generated by Scala Native. Returns 0 on success.
int ScalaNativeInit(void);

// Decodes the config JSON, starts the runtime and the poll loop, registers the callback.
// Returns 0 ok, 1 bad config, 2 internal error, 3 called from the wrong thread.
int tw_start(const char *config_json, tw_callback cb, void *ctx);

// Asks for an immediate refresh. Returns 0 or 2.
int tw_refresh(void);

// Replaces the configuration. Returns 0, 1, or 2.
int tw_set_config(const char *config_json);

// Stops the poll loop and shuts the runtime down. Returns 0 or 2.
int tw_shutdown(void);

#ifdef __cplusplus
}
#endif

#endif
